# Generated by Django 2.2.1 on 2019-05-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0002_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='dni',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
