# Generated by Django 2.2.1 on 2019-05-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0004_auto_20190502_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='map_key_first',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='responses',
            name='map_key_second',
            field=models.CharField(default='', max_length=200),
        ),
    ]
