# Generated by Django 2.2.1 on 2019-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0006_auto_20190502_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotest',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
