# Generated by Django 2.2.1 on 2019-05-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0007_autotest_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autotest',
            old_name='link',
            new_name='link_formulario',
        ),
        migrations.AddField(
            model_name='autotest',
            name='link_respuestas',
            field=models.CharField(default='', max_length=200),
        ),
    ]
