# Generated by Django 2.2.1 on 2019-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0009_datafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='key_file',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
